[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["tokio"] }
tokio = { version = "=1.24.2", default-features = false, features = ["full"] }
parking_lot = { version = "=0.12.1", features = ["nightly"] }
hyper = { git = "https://github.com/wasix-org/hyper", branch = "v0.14.18" }
libc = "=0.2.151"
socket2 = "=0.4.9"

[patch.crates-io]
libc = { git = "https://github.com/wasix-org/libc", branch = "master" }
tokio = { git = "https://github.com/wasix-org/tokio", branch = "wasix-1.24.2" }
socket2 = { git = "https://github.com/wasix-org/socket2.git", branch = "v0.4.9" }
